// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJs3Yuvo2EijDW4MG0jO_W1k6GIxt-yE',
    appId: '1:579886645281:web:93717e2297d5362d64e360',
    messagingSenderId: '579886645281',
    projectId: 'whatsappweb-ca443',
    authDomain: 'whatsappweb-ca443.firebaseapp.com',
    storageBucket: 'whatsappweb-ca443.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-nSF8tj4D9O9gWhExfiZUdpr4yYtiZv8',
    appId: '1:579886645281:android:06368e89746181df64e360',
    messagingSenderId: '579886645281',
    projectId: 'whatsappweb-ca443',
    storageBucket: 'whatsappweb-ca443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlITscOvi_uHllMAR3rMRkkcdllhMkXDk',
    appId: '1:579886645281:ios:aa2a4a86bdd7ba4264e360',
    messagingSenderId: '579886645281',
    projectId: 'whatsappweb-ca443',
    storageBucket: 'whatsappweb-ca443.appspot.com',
    iosClientId: '579886645281-nn0soji4592rh58g6dg994ecv6us62ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlITscOvi_uHllMAR3rMRkkcdllhMkXDk',
    appId: '1:579886645281:ios:aa2a4a86bdd7ba4264e360',
    messagingSenderId: '579886645281',
    projectId: 'whatsappweb-ca443',
    storageBucket: 'whatsappweb-ca443.appspot.com',
    iosClientId: '579886645281-nn0soji4592rh58g6dg994ecv6us62ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappweb',
  );
}
